apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backend-charts-application-1
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: "https://github.com/madhav8890/stage-argocd-test.git"
              revision: main
              directories:
                - path: Application-enabled/backend-application/backend/*
          - list:
              elements:
                - service: n-event-hub-web-value
                - service: n-machine-maintenance-web-value
  template:
    metadata:
      name: "{{service}}-{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: "https://github.com/madhav8890/stage-argocd-test.git"
        targetRevision: main
        path: "{{path}}"
        helm:
          valueFiles:
            - "values.yaml"
            - "../Application-values/{{service}}.yaml"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "testns"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: false
