apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master-headless
  labels:
    app: elasticsearch
spec:
  clusterIP: None # This makes it a headless service
  ports:
    - port: 9300
      name: transport
  selector:
    app: elasticsearch
