appVersion: v1
description: Elasticsearch
home: https://github.com/elastic/helm-charts
maintainers:
  - email: michael.russell@elastic.co
    name: Michael Russell
name: elasticsearch
sources:
  - https://github.com/elastic/elasticsearch
version: v1
