apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-test
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standards # Replace with your StorageClass name
