apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tools
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: "https://github.com/madhav8890/stage-argocd-test.git"
              revision: main
              directories:
                - path: Application-available/Tools*
          - list:
              elements:
                - environment: "dev"
  template:
    metadata:
      name: "{{environment}}-{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: "https://github.com/madhav8890/stage-argocd-test.git"
        targetRevision: main
        path: "{{path}}"
        helm:
          valueFiles:
            - "values.yaml"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "testns"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: false
