apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-chart-applications
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: "https://github.com/madhav8890/argo-applicationSet.git"
              revision: main
              directories:
                - path: tools-charts/*
          # - list:
          #     elements:
          #       - service: service-a
          #       - service: service-b
  template:
    metadata:
      # name: "{{service}}-{{path.basename}}"
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: "https://github.com/madhav8890/argo-applicationSet.git"
        targetRevision: main
        path: "{{path}}"
        helm:
          valueFiles:
            - "values.yaml"
            # - "values-{{service}}.yaml"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "testns"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: false
